### ISSUE TITLE
UX fix : Auto populate value in 'custom' form

### ISSUE THREAD

**Issue by odelcroi** [Boavizta/datavizta#2]
When user select an equipment in the list, the lifecycle and region should be auto populate in the 'custom form' to enhance UX and comprehension.

**Comment by AirLoren** [comment]
We will face an issue because electricity carbon intensity used by manufacturers is not the same as the one we are using to customize.
For example, the default GWP estimated by Dell for Dell E2016HV Monitor is 423 kgCO2eq (with 6 years lifespan in EU) whereas the result of our formula with same parameters (EU-27 & 6 years) is 363 kgCO2eq.

**Comment by AirLoren** [comment]
Just added lifetime autopopulate on [b5780d9](https://github.com/Boavizta/boavizta-front/commit/b5780d92e4287ccf2eaab6bef4cf8b3bc00c7999)
